const tarotDeck = [
  {
    name: "The Fool",
    number: 0,
    image: "https://i.imgur.com/p79Yjzs.png",
    meaning: "New beginnings, adventure, opportunity",
    reversed: "Carelessness, recklessness, foolishness",
    astrology: "Aries",
    element: "Fire",
    keywords: "New beginnings, adventure, opportunity",
    majorArcana: true,
    description:
      "The Fool card represents new beginnings and the start of a new journey. The figure on the card is carefree and ready for adventure, with his head held high and a small bag slung over his shoulder. He is about to step off a cliff, but he does not seem to be worried or afraid. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to embrace change and take risks, even if they seem daunting at first. Reversed, the Fool can indicate carelessness or recklessness, so it is important to balance spontaneity with caution.",
  },
  {
    name: "The Magician",
    number: 1,
    image: "https://i.imgur.com/733yhrf.png",
    meaning: "Manifestation, creation, willpower",
    reversed: "Manipulation, illusion, overconfidence",
    astrology: "Mercury",
    element: "Air",
    keywords: "Manifestation, creation, willpower",
    majorArcana: true,
    description:
      "The Magician card represents the ability to manifest your desires into reality. The figure on the card is holding a wand in one hand and a pentacle in the other, which symbolizes the union of the physical and spiritual worlds. He is also surrounded by four suits of cards, which represent the four elements: fire, water, air, and earth. This card is associated with the element of air and the zodiac sign Gemini, which both represent communication and intellect. When this card appears in a reading, it is a reminder to use your creativity and intelligence to manifest your goals. Reversed, the Magician can indicate manipulation or illusion, so it is important to be aware of your motives and intentions.",
  },
  {
    name: "The High Priestess",
    number: 2,
    image: "https://i.imgur.com/JyG8WiK.png",
    meaning: "Intuition, mystery, wisdom",
    reversed: "Mistrust, doubt, secrets revealed",
    astrology: "Moon",
    element: "Water",
    keywords: "Intuition, mystery, wisdom",
    majorArcana: true,
    description:
      "The High Priestess card represents intuition and the unknown. The figure on the card is seated in a throne, with a veil covering her face. She is surrounded by two pillars, which represent the duality of the universe. This card is associated with the element of water and the zodiac sign Pisces, which both represent intuition and spirituality. When this card appears in a reading, it is a reminder to trust your intuition and follow your inner voice. Reversed, the High Priestess can indicate mistrust or doubt, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Empress",
    number: 3,
    image: "https://i.imgur.com/vYncD06.png",
    meaning: "Femininity, creativity, abundance",
    reversed: "Emotional dependency, overindulgence, victim mentality",
    astrology: "Venus",
    element: "Earth",
    keywords: "Femininity, creativity, abundance",
    majorArcana: true,
    description:
      "The Empress card represents femininity, creativity, and abundance. The figure on the card is seated on a throne, with a crown on her head and a scepter in her hand. She is surrounded by flowers and plants, which symbolize fertility and growth. This card is associated with the element of earth and the zodiac sign Taurus, which both represent stability and sensuality. When this card appears in a reading, it is a reminder to embrace your feminine side and nurture your creativity. Reversed, the Empress can indicate emotional dependency or overindulgence, so it is important to be aware of your motives and intentions.",
  },
  {
    name: "The Emperor",
    number: 4,
    image: "https://i.imgur.com/iyMlNHP.png",
    meaning: "Authority, structure, control",
    reversed: "Domineering, stubbornness, rigidity",
    astrology: "Mars",
    element: "Fire",
    keywords: "Authority, structure, control",
    majorArcana: true,
    description:
      "The Emperor card represents authority, structure, and control. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Hierophant",
    number: 5,
    image: "https://i.imgur.com/NddPGzg.png",
    meaning: "Tradition, conformity, institutions",
    reversed: "Rebellion, non-conformity, individuality",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Tradition, conformity, institutions",
    majorArcana: true,
    description:
      "The Hierophant card represents tradition, conformity, and institutions. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Lovers",
    number: 6,
    image: "https://i.imgur.com/3FyiB0n.png",
    meaning: "Love, harmony, relationships",
    reversed: "Unrequited love, indecision, disharmony",
    astrology: "Venus",
    element: "Air",
    keywords: "Love, harmony, relationships",
    majorArcana: true,
    description:
      "The Lovers card represents love, harmony, and relationships. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Chariot",
    number: 7,
    image: "https://i.imgur.com/vJNTDTI.png",
    meaning: "Victory, control, willpower",
    reversed: "Defeat, lack of control, surrender",
    astrology: "Sun",
    element: "Fire",
    keywords: "Victory, control, willpower",
    majorArcana: true,
    description:
      "The Chariot card represents victory, control, and willpower. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Strength",
    number: 8,
    image: "https://i.imgur.com/VkHDr0H.png",
    meaning: "Courage, compassion, inner strength",
    reversed: "Weakness, fear, cruelty",
    astrology: "Leo",
    element: "Fire",
    keywords: "Courage, compassion, inner strength",
    majorArcana: true,
    description:
      "Strength card represents courage, compassion, and inner strength. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Hermit",
    number: 9,
    image: "https://i.imgur.com/uer8BNM.png",
    meaning: "Meditation, introspection, solitude",
    reversed: "Withdrawal, isolation, loneliness",
    astrology: "Virgo",
    element: "Earth",
    keywords: "Meditation, introspection, solitude",
    majorArcana: true,
    description:
      "The Hermit card represents meditation, introspection, and solitude. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Wheel of Fortune",
    number: 10,
    image: "https://i.imgur.com/IaG7hWD.png",
    meaning: "Luck, karma, cycles",
    reversed: "Bad luck, misfortune, stagnation",
    astrology: "Jupiter",
    element: "Air",
    keywords: "Luck, karma, cycles",
    majorArcana: true,
    description:
      "The Wheel of Fortune card represents luck, karma, and cycles. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Justice",
    number: 11,
    image: "https://i.imgur.com/3l5VsLx.png",
    meaning: "Fairness, truth, cause and effect",
    reversed: "Unfairness, dishonesty, imbalance",
    astrology: "Libra",
    element: "Air",
    keywords: "Fairness, truth, cause and effect",
    majorArcana: true,
    description:
      "Justice card represents fairness, truth, and cause and effect. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Hangman",
    number: 12,
    image: "https://i.imgur.com/Yq4bpJK.png",
    meaning: "Sacrifice, enlightenment, new perspective",
    reversed: "Self-sabotage, victim mentality, martyrdom",
    astrology: "Neptune",
    element: "Water",
    keywords: "Sacrifice, enlightenment, new perspective",
    majorArcana: true,
    description:
      "The Hangman card represents sacrifice, enlightenment, and new perspective. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Death",
    number: 13,
    image: "https://i.imgur.com/8HZ9aTw.png",
    meaning: "Transformation, rebirth, letting go",
    reversed: "Resistance to change, clinging to the past, stagnation",
    astrology: "Scorpio",
    element: "Water",
    keywords: "Transformation, rebirth, letting go",
    majorArcana: true,
    description:
      "Death card represents transformation, rebirth, and letting go. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Temperance",
    number: 14,
    image: "https://i.imgur.com/n2vZqGq.png",
    meaning: "Balance, moderation, patience",
    reversed: "Excess, lack of restraint, lack of self-control",
    astrology: "Sagittarius",
    element: "Fire",
    keywords: "Balance, moderation, patience",
    majorArcana: true,
    description:
      "Temperance card represents balance, moderation, and patience. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Devil",
    number: 15,
    image: "https://i.imgur.com/D4wFdDH.png",
    meaning: "Addiction, materialism, control",
    reversed: "Freedom, release, liberation",
    astrology: "Saturn",
    element: "Earth",
    keywords: "Addiction, materialism, control",
    majorArcana: true,
    description:
      "The Devil card represents addiction, materialism, and control. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Tower",
    number: 16,
    image: "https://i.imgur.com/iuEIFkj.png",
    meaning: "Sudden change, upheaval, revelation",
    reversed: "Sudden change averted, disruption avoided",
    astrology: "Mars",
    element: "Fire",
    keywords: "Sudden change, upheaval, revelation",
    majorArcana: true,
    description:
      "The Tower card represents sudden change, upheaval, and revelation. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Star",
    number: 17,
    image: "https://i.imgur.com/Or0mIXs.png",
    meaning: "Hope, renewal, inspiration",
    reversed: "Disappointment, despair, hopelessness",
    astrology: "Jupiter",
    element: "Air",
    keywords: "Hope, renewal, inspiration",
    majorArcana: true,
    description:
      "The Star card represents hope, renewal, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Moon",
    number: 18,
    image: "https://i.imgur.com/PupTujb.png",
    meaning: "Illusions, fears, intuition",
    reversed: "Clarity, reassurance, lucidity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Illusions, fears, intuition",
    majorArcana: true,
    description:
      "The Moon card represents illusions, fears, and intuition. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The Sun",
    number: 19,
    image: "blob:https://imgur.com/2bec9d47-b029-4f32-87fa-c4743f938054",
    meaning: "Happiness, success, fulfillment",
    reversed: "Depression, disappointment, blocked creativity",
    astrology: "Sun",
    element: "Fire",
    keywords: "Happiness, success, fulfillment",
    majorArcana: true,
    description:
      "The Sun card represents happiness, success, and fulfillment. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Judgement",
    number: 20,
    image: "https://i.imgur.com/AteOoAM.png",
    meaning: "Awakening, rebirth, atonement",
    reversed: "Lack of self-awareness, missed opportunities",
    astrology: "Uranus",
    element: "Air",
    keywords: "Awakening, rebirth, atonement",
    majorArcana: true,
    description:
      "Judgement represents awakening, rebirth, and atonement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "The World",
    number: 21,
    image: "https://i.imgur.com/ZvIBzzx.png",
    meaning: "Completion, fulfillment, success",
    reversed: "Incompletion, lack of fulfillment, stagnation",
    astrology: "Saturn",
    element: "Earth",
    keywords: "Completion, fulfillment, success",
    majorArcana: true,
    description:
      "The World represents completion, fulfillment, and success. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ace of Wands",
    number: 1,
    image: "https://i.imgur.com/VW9U5lT.png",
    meaning: "Creation, inspiration, new beginnings",
    reversed: "Lack of direction, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Creation, inspiration, new beginnings",
    majorArcana: false,
    description:
      "The Ace of Wands represents creation, inspiration, and new beginnings. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Two of Wands",
    number: 2,
    image: "https://i.imgur.com/PKZuGwa.png",
    meaning: "Expansion, adventure, exploration",
    reversed: "Lack of direction, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Expansion, adventure, exploration",
    majorArcana: false,
    description:
      "The Two of Wands represents expansion, adventure, and exploration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Three of Wands",
    number: 3,
    image: "https://i.imgur.com/P1g2Tjw.png",
    meaning: "Expansion, adventure, exploration",
    reversed: "Lack of direction, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Expansion, adventure, exploration",
    majorArcana: false,
    description:
      "The Three of Wands represents expansion, adventure, and exploration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Four of Wands",
    number: 4,
    image: "https://i.imgur.com/AxzRXus.png",
    meaning: "Celebration, success, achievement",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Celebration, success, achievement",
    majorArcana: false,
    description:
      "The Four of Wands represents celebration, success, and achievement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Five of Wands",
    number: 5,
    image: "https://i.imgur.com/l6IjOHE.png",
    meaning: "Competition, conflict, struggle",
    reversed: "Lack of competition, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Competition, conflict, struggle",
    majorArcana: false,
    description:
      "The Five of Wands represents competition, conflict, and struggle. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Six of Wands",
    number: 6,
    image: "https://i.imgur.com/ICXEo6Q.png",
    meaning: "Victory, success, recognition",
    reversed: "Lack of recognition, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Victory, success, recognition",
    majorArcana: false,
    description:
      "The Six of Wands represents victory, success, and recognition. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Seven of Wands",
    number: 7,
    image: "https://i.imgur.com/0Vsn0S3.png",
    meaning: "Defending your position, standing your ground",
    reversed: "Lack of defense, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Defending your position, standing your ground",
    majorArcana: false,
    description:
      "The Seven of Wands represents defending your position, standing your ground. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Eight of Wands",
    number: 8,
    image: "https://i.imgur.com/BDiCpny.png",
    meaning: "Rapid action, progress, movement",
    reversed: "Lack of progress",
    astrology: "Aries",
    element: "Fire",
    keywords: "Rapid action, progress, movement",
    majorArcana: false,
    description:
      "The Eight of Wands represents rapid action, progress, and movement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Nine of Wands",
    number: 9,
    image: "https://i.imgur.com/uS6IqHK.png",
    meaning: "Defending your position, standing your ground",
    reversed: "Lack of defense, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Defending your position, standing your ground",
    majorArcana: false,
    description:
      "The Nine of Wands represents defending your position, standing your ground. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ten of Wands",
    number: 10,
    image: "https://i.imgur.com/0iUbX7q.png",
    meaning: "Overwhelm, burden, responsibility",
    reversed: "Lack of responsibility, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Overwhelm, burden, responsibility",
    majorArcana: false,
    description:
      "The Ten of Wands represents overwhelm, burden, and responsibility. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Page of Wands",
    number: 11,
    image: "https://i.imgur.com/xCrekJM.png",
    meaning: "Enthusiasm, creativity, inspiration",
    reversed: "Lack of enthusiasm, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Enthusiasm, creativity, inspiration",
    majorArcana: false,
    description:
      "The Page of Wands represents enthusiasm, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Knight of Wands",
    number: 12,
    image: "https://i.imgur.com/mzW55xF.png",
    meaning: "Action, passion, movement",
    reversed: "Lack of action, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Action, passion, movement",
    majorArcana: false,
    description:
      "The Knight of Wands represents action, passion, and movement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Queen of Wands",
    number: 13,
    image: "https://i.imgur.com/K81T4Jr.png",
    meaning: "Passion, creativity, inspiration",
    reversed: "Lack of passion, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Passion, creativity, inspiration",
    majorArcana: false,
    description:
      "The Queen of Wands represents passion, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "King of Wands",
    number: 14,
    image: "https://i.imgur.com/EkJAKrk.png",
    meaning: "Passion, creativity, inspiration",
    reversed: "Lack of passion, stagnation, blocked creativity",
    astrology: "Aries",
    element: "Fire",
    keywords: "Passion, creativity, inspiration",
    majorArcana: false,
    description:
      "The King of Wands represents passion, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ace of Cups",
    number: 1,
    image: "https://i.imgur.com/YRSnXgq.png",
    meaning: "Love, compassion, creativity",
    reversed: "Lack of love, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Love, compassion, creativity",
    majorArcana: false,
    description:
      "The Ace of Cups represents love, compassion, and creativity. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Two of Cups",
    number: 2,
    image: "https://i.imgur.com/uxDiKK8.png",
    meaning: "Love, compassion, creativity",
    reversed: "Lack of love, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Love, compassion, creativity",
    majorArcana: false,
    description:
      "The Two of Cups represents love, compassion, and creativity. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Three of Cups",
    number: 3,
    image: "https://i.imgur.com/5M8ZPHu.png",
    meaning: "Celebration, friendship, community",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Celebration, friendship, community",
    majorArcana: false,
    description:
      "The Three of Cups represents celebration, friendship, and community. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Four of Cups",
    number: 4,
    image: "https://i.imgur.com/aOhQMYD.png",
    meaning: "Celebration, success, achievement",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Celebration, success, achievement",
    majorArcana: false,
    description:
      "The Four of Cups represents celebration, success, and achievement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Five of Cups",
    number: 5,
    image: "https://i.imgur.com/nZAsSIS.png",
    meaning: "Loss, grief, sadness",
    reversed: "Lack of loss, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Loss, grief, sadness",
    majorArcana: false,
    description:
      "The Five of Cups represents loss, grief, and sadness. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Six of Cups",
    number: 6,
    image: "https://i.imgur.com/Sv7vKPd.png",
    meaning: "Celebration, success, achievement",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Celebration, success, achievement",
    majorArcana: false,
    description:
      "The Six of Cups represents celebration, success, and achievement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Seven of Cups",
    number: 7,
    image: "https://i.imgur.com/6ZvZ2Y5.png",
    meaning: "Fantasy, imagination, creativity",
    reversed: "Lack of fantasy, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Fantasy, imagination, creativity",
    majorArcana: false,
    description:
      "The Seven of Cups represents fantasy, imagination, and creativity. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Eight of Cups",
    number: 8,
    image: "https://i.imgur.com/IC0ykzn.png",
    meaning: "Rapid action, progress, movement",
    reversed: "Lack of progress, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Rapid action, progress, movement",
    majorArcana: false,
    description:
      "The Eight of Cups represents rapid action, progress, and movement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Nine of Cups",
    number: 9,
    image: "https://i.imgur.com/cKrwgG3.png",
    meaning: "Celebration, success, achievement",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Celebration, success, achievement",
    majorArcana: false,
    description:
      "The Nine of Cups represents celebration, success, and achievement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ten of Cups",
    number: 10,
    image: "https://i.imgur.com/FnFRe3U.png",
    meaning: "Celebration, success, achievement",
    reversed: "Lack of celebration, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Celebration, success, achievement",
    majorArcana: false,
    description:
      "The Ten of Cups represents celebration, success, and achievement. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Page of Cups",
    number: 11,
    image: "https://i.imgur.com/pLoLlDu.png",
    meaning: "Imagination, creativity, inspiration",
    reversed: "Lack of imagination, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Imagination, creativity, inspiration",
    majorArcana: false,
    description:
      "The Page of Cups represents imagination, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Knight of Cups",
    number: 12,
    image: "https://i.imgur.com/WgovFU8.png",
    meaning: "Imagination, creativity, inspiration",
    reversed: "Lack of imagination, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Imagination, creativity, inspiration",
    majorArcana: false,
    description:
      "The Knight of Cups represents imagination, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Queen of Cups",
    number: 13,
    image: "https://i.imgur.com/YGyYNOo.png",
    meaning: "Imagination, creativity, inspiration",
    reversed: "Lack of imagination, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Imagination, creativity, inspiration",
    majorArcana: false,
    description:
      "The Queen of Cups represents imagination, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "King of Cups",
    number: 14,
    image: "https://i.imgur.com/h85xD5q.png",
    meaning: "Imagination, creativity, inspiration",
    reversed: "Lack of imagination, stagnation, blocked creativity",
    astrology: "Cancer",
    element: "Water",
    keywords: "Imagination, creativity, inspiration",
    majorArcana: false,
    description:
      "The King of Cups represents imagination, creativity, and inspiration. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ace of Swords",
    number: 1,
    image: "https://i.imgur.com/FxNBvNT.png",
    meaning: "Truth, clarity, wisdom",
    reversed: "Lack of truth, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Truth, clarity, wisdom",
    majorArcana: false,
    description:
      "The Ace of Swords represents truth, clarity, and wisdom. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Two of Swords",
    number: 2,
    image: "https://i.imgur.com/Qnn4KNF.png",
    meaning: "Balance, harmony, peace",
    reversed: "Lack of balance, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Balance, harmony, peace",
    majorArcana: false,
    description:
      "The Two of Swords represents balance, harmony, and peace. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Three of Swords",
    number: 3,
    image: "https://i.imgur.com/kArCmh6.png",
    meaning: "Heartbreak, sadness, grief",
    reversed: "Lack of heartbreak, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Heartbreak, sadness, grief",
    majorArcana: false,
    description:
      "The Three of Swords represents heartbreak, sadness, and grief. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Four of Swords",
    number: 4,
    image: "https://i.imgur.com/srYP8ze.png",
    meaning: "Rest, relaxation, meditation",
    reversed: "Lack of rest, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Rest, relaxation, meditation",
    majorArcana: false,
    description:
      "The Four of Swords represents rest, relaxation, and meditation. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Five of Swords",
    number: 5,
    image: "https://i.imgur.com/5kTvtbN.png",
    meaning: "Conflict, competition, struggle",
    reversed: "Lack of conflict, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Conflict, competition, struggle",
    majorArcana: false,
    description:
      "The Five of Swords represents conflict, competition, and struggle. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Six of Swords",
    number: 6,
    image: "https://i.imgur.com/R9cN5FN.png",
    meaning: "Journey, travel, transition",
    reversed: "Lack of journey, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Journey, travel, transition",
    majorArcana: false,
    description:
      "The Six of Swords represents journey, travel, and transition. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Seven of Swords",
    number: 7,
    image: "https://i.imgur.com/U7mMS2v.png",
    meaning: "Deception, trickery, manipulation",
    reversed: "Lack of deception, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Deception, trickery, manipulation",
    majorArcana: false,
    description:
      "The Seven of Swords represents deception, trickery, and manipulation. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Eight of Swords",
    number: 8,
    image: "https://i.imgur.com/P5ZkFxj.png",
    meaning: "Imprisonment, restriction, limitation",
    reversed: "Lack of imprisonment, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Imprisonment, restriction, limitation",
    majorArcana: false,
    description:
      "The Eight of Swords represents imprisonment, restriction, and limitation. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Nine of Swords",
    number: 9,
    image: "https://i.imgur.com/SRBGvs8.png",
    meaning: "Anxiety, worry, fear",
    reversed: "Lack of anxiety, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Anxiety, worry, fear",
    majorArcana: false,
    description:
      "The Nine of Swords represents anxiety, worry, and fear. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ten of Swords",
    number: 10,
    image: "https://i.imgur.com/eDkvyiP.png",
    meaning: "Defeat, failure, loss",
    reversed: "Lack of defeat, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Defeat, failure, loss",
    majorArcana: false,
    description:
      "The Ten of Swords represents defeat, failure, and loss. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Page of Swords",
    number: 11,
    image: "https://i.imgur.com/1TjQbLM.png",
    meaning: "Truth, clarity, wisdom",
    reversed: "Lack of truth, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Truth, clarity, wisdom",
    majorArcana: false,
    description:
      "The Page of Swords represents truth, clarity, and wisdom. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Knight of Swords",
    number: 12,
    image: "https://i.imgur.com/GFCQV1u.png",
    meaning: "Truth, clarity, wisdom",
    reversed: "Lack of truth, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Truth, clarity, wisdom",
    majorArcana: false,
    description:
      "The Knight of Swords represents truth, clarity, and wisdom. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Queen of Swords",
    number: 13,
    image: "https://i.imgur.com/bJUpIIi.png",
    meaning: "Truth, clarity, wisdom",
    reversed: "Lack of truth, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Truth, clarity, wisdom",
    majorArcana: false,
    description:
      "The Queen of Swords represents truth, clarity, and wisdom. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "King of Swords",
    number: 14,
    image: "https://i.imgur.com/Ra2cC03.png",
    meaning: "Truth, clarity, wisdom",
    reversed: "Lack of truth, stagnation, blocked creativity",
    astrology: "Libra",
    element: "Air",
    keywords: "Truth, clarity, wisdom",
    majorArcana: false,
    description:
      "The King of Swords represents truth, clarity, and wisdom. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ace of Pentacles",
    number: 1,
    image: "https://i.imgur.com/FSsumdt.png",
    meaning: "Abundance, prosperity, wealth",
    reversed: "Lack of abundance, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Abundance, prosperity, wealth",
    majorArcana: false,
    description:
      "The Ace of Pentacles represents abundance, prosperity, and wealth. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Two of Pentacles",
    number: 2,
    image: "https://i.imgur.com/3VRc1u6.png",
    meaning: "Balance, harmony, peace",
    reversed: "Lack of balance, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Balance, harmony, peace",
    majorArcana: false,
    description:
      "The Two of Pentacles represents balance, harmony, and peace. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Three of Pentacles",
    number: 3,
    image: "https://i.imgur.com/mRPmJOT.png",
    meaning: "Collaboration, teamwork, partnership",
    reversed: "Lack of collaboration, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Collaboration, teamwork, partnership",
    majorArcana: false,
    description:
      "The Three of Pentacles represents collaboration, teamwork, and partnership. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Four of Pentacles",
    number: 4,
    image: "https://i.imgur.com/z7pJ62c.png",
    meaning: "Materialism, greed, hoarding",
    reversed: "Lack of materialism, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Materialism, greed, hoarding",
    majorArcana: false,
    description:
      "The Four of Pentacles represents materialism, greed, and hoarding. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Five of Pentacles",
    number: 5,
    image: "https://i.imgur.com/3noDxjv.png",
    meaning: "Poverty, scarcity, loss",
    reversed: "Lack of poverty, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Poverty, scarcity, loss",
    majorArcana: false,
    description:
      "The Five of Pentacles represents poverty, scarcity, and loss. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Six of Pentacles",
    number: 6,
    image: "https://i.imgur.com/Ze3Upht.png",
    meaning: "Generosity, charity, giving",
    reversed: "Lack of generosity, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Generosity, charity, giving",
    majorArcana: false,
    description:
      "The Six of Pentacles represents generosity, charity, and giving. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Seven of Pentacles",
    number: 7,
    image: "https://i.imgur.com/B8C1Gha.png",
    meaning: "Hard work, patience, perseverance",
    reversed: "Lack of hard work, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Hard work, patience, perseverance",
    majorArcana: false,
    description:
      "The Seven of Pentacles represents hard work, patience, and perseverance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Eight of Pentacles",
    number: 8,
    image: "https://i.imgur.com/TRE46xO.png",
    meaning: "Hard work, patience, perseverance",
    reversed: "Lack of hard work, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Hard work, patience, perseverance",
    majorArcana: false,
    description:
      "The Eight of Pentacles represents hard work, patience, and perseverance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Nine of Pentacles",
    number: 9,
    image: "https://i.imgur.com/vi6TAeT.png",
    meaning: "Luxury, comfort, pleasure",
    reversed: "Lack of luxury, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Luxury, comfort, pleasure",
    majorArcana: false,
    description:
      "The Nine of Pentacles represents luxury, comfort, and pleasure. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Ten of Pentacles",
    number: 10,
    image: "https://i.imgur.com/MOkos0Q.png",
    meaning: "Wealth, prosperity, abundance",
    reversed: "Lack of wealth, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Wealth, prosperity, abundance",
    majorArcana: false,
    description:
      "The Ten of Pentacles represents wealth, prosperity, and abundance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Page of Pentacles",
    number: 11,
    image: "https://i.imgur.com/38vn0jI.png",
    meaning: "Wealth, prosperity, abundance",
    reversed: "Lack of wealth, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Wealth, prosperity, abundance",
    majorArcana: false,
    description:
      "The Page of Pentacles represents wealth, prosperity, and abundance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Knight of Pentacles",
    number: 12,
    image: "https://i.imgur.com/5Ex6u0W.png",
    meaning: "Wealth, prosperity, abundance",
    reversed: "Lack of wealth, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Wealth, prosperity, abundance",
    majorArcana: false,
    description:
      "The Knight of Pentacles represents wealth, prosperity, and abundance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "Queen of Pentacles",
    number: 13,
    image: "https://i.imgur.com/Ws8seiJ.png",
    meaning: "Wealth, prosperity, abundance",
    reversed: "Lack of wealth, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Wealth, prosperity, abundance",
    majorArcana: false,
    description:
      "The Queen of Pentacles represents wealth, prosperity, and abundance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
  {
    name: "King of Pentacles",
    number: 14,
    image: "https://i.imgur.com/pkjtC9A.png",
    meaning: "Wealth, prosperity, abundance",
    reversed: "Lack of wealth, stagnation, blocked creativity",
    astrology: "Taurus",
    element: "Earth",
    keywords: "Wealth, prosperity, abundance",
    majorArcana: false,
    description:
      "The King of Pentacles represents wealth, prosperity, and abundance. The figure on the card is seated on a throne, with a crown on his head and a scepter in his hand. He is surrounded by a wall, which symbolizes protection and security. This card is associated with the element of fire and the zodiac sign Aries, which both represent energy, passion, and impulsiveness. When this card appears in a reading, it is a reminder to take control of your life and be assertive. Reversed, the Emperor can indicate domineering or stubbornness, so it is important to be open to new ideas and experiences.",
  },
];

export { tarotDeck };
